import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./components/AuthProvider";
import { Toaster } from "./components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} bg-gray-900 text-zinc-100 ${geistSans.variable} ${geistMono.variable}`}
      >
        <AuthProvider>
          {/* konten utama, tanpa pb-24 supaya tidak ada space aneh */}
          <main className="min-h-screen">{children}</main>

          {/* toaster notification */}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
